-- 1. Tabela stacji
CREATE TABLE stacje (
    stacja_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    miasto VARCHAR2(100) NOT NULL,
    kraj VARCHAR2(100) DEFAULT 'Polska',
    szerokosc_geo NUMBER(9,6),
    dlugosc_geo NUMBER(9,6),
    CONSTRAINT unq_miasto UNIQUE (miasto, kraj)
);

-- 2. Tabela pomiarów
CREATE TABLE pomiary (
    pomiar_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    stacja_id NUMBER REFERENCES stacje(stacja_id),
    data_pomiaru TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temperatura NUMBER(4,1) NOT NULL,
    wilgotnosc NUMBER(3) CHECK (wilgotnosc BETWEEN 0 AND 100),
    cisnienie NUMBER(5),
    opis_pogody VARCHAR2(50)
);

-- 3. Archiwum
CREATE TABLE archiwum_pomiarow (
    arch_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    oryginalne_id NUMBER,
    stacja_id NUMBER,
    data_pomiaru TIMESTAMP,
    data_usuniecia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    powod_usuniecia VARCHAR2(255)
);

-- 4. Logi systemowe
CREATE TABLE logi_systemowe (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    uzytkownik VARCHAR2(50),
    operacja VARCHAR2(50),
    tabela_nazwa VARCHAR2(50),
    data_zdarzenia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    szczegoly VARCHAR2(4000)
);

-- 5. Raporty miesięczne
CREATE TABLE raporty_miesieczne (
    raport_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    stacja_id NUMBER REFERENCES stacje(stacja_id),
    miesiac NUMBER(2),
    rok NUMBER(4),
    srednia_temp NUMBER(5,2),
    max_temp NUMBER(4,1),
    min_temp NUMBER(4,1),
    data_wygenerowania TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
